<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2013-02-25 10:42:37                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	abstract class ProtoCreatedAndModified extends AutoProtoCreatedAndModified {/*_*/}
?>