<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2013-02-26 20:45:33                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoJobSkill extends AutoProtoJobSkill {/*_*/}
?>