<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2013-03-14 12:40:16                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoJobApplication extends AutoProtoJobApplication {/*_*/}
?>