<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2013-02-25 13:58:31                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoJob extends AutoProtoJob {/*_*/}
?>