<?php 

// shared classes
define(
        'PATH_CLASSES',
        PATH_BASE.'src/classes/'
);

// shared templates
define(
        'PATH_TEMPLATES',
        PATH_BASE.'src/tmpl/'
);

// shared templates
define(
        'PATH_CONTROLLERS',
        PATH_BASE.'src/controllers/'
);

ini_set(
		'include_path', get_include_path().PATH_SEPARATOR
		.PATH_CLASSES.PATH_SEPARATOR
		.PATH_CLASSES.'DAOs'.PATH_SEPARATOR
		.PATH_CLASSES.'Business'.PATH_SEPARATOR
		.PATH_CLASSES.'Proto'.PATH_SEPARATOR
		.PATH_CLASSES.'Exceptions'.PATH_SEPARATOR
		
//		.PATH_CLASSES.'Flow'.PATH_SEPARATOR
//		.PATH_CLASSES.'Flow'.DIRECTORY_SEPARATOR.'common'.PATH_SEPARATOR
//		.PATH_CLASSES.'Flow'.DIRECTORY_SEPARATOR.'billing'.PATH_SEPARATOR
		
//		.PATH_CLASSES.'Flow'.DIRECTORY_SEPARATOR.'auth'.PATH_SEPARATOR
//		.PATH_CLASSES.'Flow'.DIRECTORY_SEPARATOR.'auth'.DIRECTORY_SEPARATOR.'company'.PATH_SEPARATOR
		
//		.PATH_CLASSES.'Flow'.DIRECTORY_SEPARATOR.'tm'.PATH_SEPARATOR
//		.PATH_CLASSES.'Flow'.DIRECTORY_SEPARATOR.'tm'.DIRECTORY_SEPARATOR.'report'.PATH_SEPARATOR	
//		.PATH_CLASSES.'Flow'.DIRECTORY_SEPARATOR.'tm'.DIRECTORY_SEPARATOR.'task'.PATH_SEPARATOR
		
		.PATH_CLASSES.'Interfaces'.PATH_SEPARATOR
		.PATH_CLASSES.'Bases'.PATH_SEPARATOR
		
		.PATH_CLASSES.'Utils'.PATH_SEPARATOR
		.PATH_CLASSES.'Utils'.DIRECTORY_SEPARATOR.'HttpClientHandlers'.PATH_SEPARATOR
		.PATH_CLASSES.'Utils'.DIRECTORY_SEPARATOR.'FileWorkers'.PATH_SEPARATOR
		.PATH_CLASSES.'Utils'.DIRECTORY_SEPARATOR.'Notifier'.PATH_SEPARATOR
		.PATH_CLASSES.'Utils'.DIRECTORY_SEPARATOR.'SimpleMail'.PATH_SEPARATOR
		.PATH_CLASSES.'Utils'.DIRECTORY_SEPARATOR.'delivery'.PATH_SEPARATOR
		
		.PATH_CLASSES.'Utils'.DIRECTORY_SEPARATOR.'common'.PATH_SEPARATOR
//		.PATH_CLASSES.'Utils'.DIRECTORY_SEPARATOR.'billing'.PATH_SEPARATOR
//		.PATH_CLASSES.'Utils'.DIRECTORY_SEPARATOR.'taskTemplates'.PATH_SEPARATOR
		
//		.PATH_CLASSES.'GUI'.PATH_SEPARATOR
//		.PATH_CLASSES.'GUI'.DIRECTORY_SEPARATOR.'Helpers'.PATH_SEPARATOR
//		.PATH_CLASSES.'GUI'.DIRECTORY_SEPARATOR.'Widgets'.PATH_SEPARATOR
//		.PATH_CLASSES.'GUI'.DIRECTORY_SEPARATOR.'Widgets'.DIRECTORY_SEPARATOR.'Html'.PATH_SEPARATOR

		.PATH_CLASSES.'Auto'.DIRECTORY_SEPARATOR.'Business'.PATH_SEPARATOR
		.PATH_CLASSES.'Auto'.DIRECTORY_SEPARATOR.'Proto'.PATH_SEPARATOR
		.PATH_CLASSES.'Auto'.DIRECTORY_SEPARATOR.'DAOs'.PATH_SEPARATOR
		
		
		// Handlers-COntrollers
		.PATH_CLASSES.'..'.DS.'controllers'.PATH_SEPARATOR
		.PATH_CLASSES.'..'.DS.'controllers'.DS.'admin'.PATH_SEPARATOR
		.PATH_CLASSES.'..'.DS.'controllers'.DS.'auth'.PATH_SEPARATOR
		.PATH_CLASSES.'..'.DS.'controllers'.DS.'my'.PATH_SEPARATOR
		.PATH_CLASSES.'..'.DS.'controllers'.DS.'json'.PATH_SEPARATOR
		
	);
	
//var_dump($a);
	//define('PATH_XHPROF', PATH_BASE.'lib'.DS.'xhprof'.DS.'utils'.DS);