<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2013-02-25 10:42:37                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class AjaxDataResponse extends AutoAjaxDataResponse implements Prototyped
	{
		/**
		 * @return AjaxDataResponse
		**/
		public static function create()
		{
			return new self;
		}
		
		
		/**
		 * @return ProtoAjaxDataResponse
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoAjaxDataResponse');
		}
		
		// your brilliant stuff goes here
                
                public function toArray(){
                    return array();
                }
	}
?>